name: Build ZMK firmware (nix)

on:
  workflow_dispatch:
  push:
    paths:
      - boards/**
      - zephyr/**
      - config/**
      - build.yaml

jobs:
  build:
    uses: urob/zmk-actions/.github/workflows/build-user-config.yml@main
    with:
      toolchain: zephyr

  build-dfu:
    runs-on: ubuntu-latest
    needs: build
    env:
      build_dir: ${{ needs.build.outputs.build_dir }}
      artifact_name: ${{ needs.build.outputs.artifact_name }}
    steps:
      - uses: actions/checkout@v3
      - name: Download firmware artifact
        uses: actions/download-artifact@v4
        with:
          name: firmware
          path: ${{ github.workspace }}/artifacts

      - name: Build DFU package
        run: |
          sudo apt update
          sudo apt install -y python3-venv
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip adafruit-nrfutil
          python3 -m adafruit_nrfutil dfu genpkg \
            --dev-type 0x0052 \
            --application "${{ github.workspace }}/artifacts/${{ env.artifact_name }}.uf2" \
            "${{ github.workspace }}/artifacts/${{ env.artifact_name }}.zip"
      - name: Upload DFU artifact
        uses: actions/upload-artifact@v4
        with:
          name: "${{ env.artifact_name }}-dfu"
          path: "${{ env.build_dir }}/artifacts/${{ env.artifact_name }}.zip"
