name: Build ZMK firmware (nix)

on:
  workflow_dispatch:
  push:
    paths:
      - boards/**
      - zephyr/**
      - config/**
      - build.yaml

jobs:
  build:
    uses: urob/zmk-actions/.github/workflows/build-user-config.yml@main
    with:
      toolchain: zephyr
  merge:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v5
        with:
          name: ${{ github.event.inputs.archive_name || 'merged-artifacts' }}
          pattern: artifact-*
          delete-merged: true

  build-dfu:
    runs-on: ubuntu-latest
    needs: merge
    env:
      build_dir: ${{ needs.build.outputs.build_dir }}
      artifact_name: ${{ needs.build.outputs.artifact_name }}
      archive_name: ${{ github.event.inputs.archive_name }}
    steps:
      - uses: actions/checkout@v3
  
      - name: Download merged artifact
        uses: actions/download-artifact@v5
        with:
          name: ${{ env.archive_name }}
          path: ${{ github.workspace }}/artifacts
  
      - name: Build DFU package
        run: |
          sudo apt update
          sudo apt install -y pipx
          pipx run --spec adafruit-nrfutil adafruit-nrfutil dfu genpkg \
            --dev-type 0x0052 \
            --application "${{ github.workspace }}/artifacts/${{ env.artifact_name }}.uf2" \
            "${{ github.workspace }}/artifacts/${{ env.artifact_name }}.zip"
  
      - name: Upload DFU artifact
        uses: actions/upload-artifact@v5
        with:
          name: "${{ env.artifact_name }}-dfu"
          path: "${{ github.workspace }}/artifacts/${{ env.artifact_name }}.zip"
