name: Build ZMK firmware (nix)
on:
  workflow_dispatch:
  push:
    paths:
      - boards/**
      - zephyr/**
      - config/**
      - build.yaml

jobs:
  build:
    uses: urob/zmk-actions/.github/workflows/build-user-config.yml@main
    with:
      toolchain: zephyr

  dfu:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: zmkfirmware/zmk-dev-arm:3.5-branch
    env:
      artifact_name: "default"
      build_dir: "build"
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install tools
        run: |
          python3 -m pip install adafruit-nrfutil
          pip install uf2conv

      - name: Convert UF2 to HEX
        run: |
          mkdir -p "${{ env.build_dir }}/zephyr"
          uf2conv.py -o "${{ env.build_dir }}/zephyr/zmk.hex" "path/to/build/zmk.uf2"

      - name: Build DFU package
        run: |
          adafruit-nrfutil dfu genpkg \
            --dev-type 0x0052 \
            --application "${{ env.build_dir }}/zephyr/zmk.hex" \
            "${{ env.build_dir }}/zephyr/${{ env.artifact_name }}.zip"

      - name: Upload DFU artifact
        uses: actions/upload-artifact@v3
        with:
          name: "${{ env.artifact_name }}-dfu"
          path: "${{ env.build_dir }}/zephyr/${{ env.artifact_name }}.zip"
