name: Build ZMK firmware (nix)

on:
  workflow_dispatch:
  push:
    paths:
      - boards/**
      - zephyr/**
      - config/**
      - build.yaml

jobs:
  build:
    uses: urob/zmk-actions/.github/workflows/build-user-config.yml@main
    with:
      toolchain: zephyr

  build-dfu:
    runs-on: ubuntu-latest
    needs: build
    env:
      build_dir: ${{ needs.build.outputs.build_dir }}
      artifact_name: firmware   # hardcoded to match the artifact name from the build job
    steps:
      - uses: actions/checkout@v3

      - name: Download firmware artifact
        uses: actions/download-artifact@v5
        with:
          name: artifact-${{ needs.build.outputs.artifact_name }}
          path: ${{ github.workspace }}/artifacts

      - name: Build DFU package
        run: |
          sudo apt update
          sudo apt install -y pipx
          pipx run --spec adafruit-nrfutil adafruit-nrfutil dfu genpkg \
            --dev-type 0x0052 \
            --application "${{ github.workspace }}/artifacts/${{ env.artifact_name }}.uf2" \
            "${{ github.workspace }}/artifacts/${{ env.artifact_name }}.zip"

      - name: Upload DFU artifact
        uses: actions/upload-artifact@v5
        with:
          name: "${{ env.artifact_name }}-dfu"
          path: "${{ github.workspace }}/artifacts/${{ env.artifact_name }}.zip"
